install.packages("forecast")
install.packages("readxl")
library(readxl)
df<-read_excel("C:/Users/user/Desktop/R/ic7.xlsx",col_names =TRUE,na="")
df_ts<-ts(df[,12],start=c(2003,1),end=c(2012,12),frequency=12)
df_ts
par(oma=c(0,0,0,0))
par(mfrow=c(1,1))
plot(df_ts,main="<Figure1>",ylab="Air Passenger",xlab="Year")
df_comp<-decompose(df_ts)
plot(df_comp)
library(tseries)
plot(diff(log(df_ts)))
par(oma=c(0,0,5,0))
par(mfrow = c(1,2))
acf(diff(log(df_ts)) , main="ACF", ylab="")
pacf(diff(log(df_ts)), main="PACF", ylab="")
df_adjusted <- df_ts - df_comp$seasonal
par(mfrow = c(1,1))
plot.ts(df_adjusted, main = "Passenger - seasonal factor")
library(TTR)
library(forecast)
auto.arima(df_ts)
tsdiag(auto.arima(diff(log(df_ts))))
set.seed(1)
series <- ts(rnorm(100),f=6)
df_arima<-arima(df_ts,order=c(1,0,0),seasonal = list(order=c(0,1,1),period=72),method="ML")
summary(df_arima)
df_fcast<-forecast(df_arima,h=72)
df_fcast
par(oma=c(0,0,0,0))
par(mfrow=c(1,1))
plot(forecast(df_arima,h=12))
legend("topleft",c("Actual","Prediction"),col=c(1,4),lty=c(1,1))